name: Release draft

permissions:
  id-token: write
  contents: read
  attestations: write

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
        node-version: 24

      - name: Deps
        run: |
        npm install --global pnpm
        pnpm i

      - name: Build plugin(s)
        run: pnpm lune ci

      - name: Run CI
        run: |
        cp -r static/* dist || true
        pnpm lune ci
    
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          repository: nilFinx/ShelterOCCR
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/shelteroccr/*